# Cloud Build configuration for automated deployment
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
  
  # Build the React app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
  
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    timeout: '1600s'

options:
  machineType: 'N1_HIGHCPU_8'

